# This is a basic workflow that is manually triggered

name: Bump Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  bump-patch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Bump Semantic Version
      # You may pin to the exact commit or the version.
      # uses: jessicalostinspace/bump-semantic-version-action@b915bfb0a53965f8206898d80ca6a9b5efb6817f
      uses: jessicalostinspace/bump-semantic-version-action@v1.0.1
      with:
        # A semantic version you want to increase
        semantic-version: 1.0.0
        # MAJOR, MINOR, or PATCH
        version-type: PATCH
